name: Compile & Render Document

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  compile_and_render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout al repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias de LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Compilar LaTeX a PDF
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: tesina.tex
      
      - name: Instalar pdftoppm (PDF a imagen)
        run: sudo apt-get install -y poppler-utils

      - name: Convertir portada a imagen
        run: |
          pdftoppm -png tesina.pdf recursos/portada -f 1 -l 1

      - name: Subir archivos generados
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
        
          git add tesina.pdf recursos/portada.png
          git commit -m "Compile & Render Document Action"
          git push origin master
        
